theme: midnight
title: Portafolio Digital Integrador - Diplomado en Inteligencia Artificial
description: Registro de actividades desarrolladas en el Diplomado en Inteligencia Artificial para transformar la docencia universitaria. Universidad Católica de Temuco
